server:
  port: 8080
  servlet:
    context-path: /

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: bangae1
    password: fpdlwms1
    url: jdbc:mysql://bangae2.iptime.org:3306/test
    driver-class-name: com.mysql.jdbc.Driver

